def bfe():
  rf = RandomForestRegressor(n_estimators = 10)
  rf.fit(X_train2,y_train)
  y_pred = rf.predict(X_test2)
  import matplotlib.gridspec as gridspec
  fig = plt.figure(figsize=(12,5))
  grid = gridspec.GridSpec(ncols=2, nrows=1, figure=fig)
  ax1 = fig.add_subplot(grid[0, 0])
  ax2 = fig.add_subplot(grid[0, 1])
  sns.scatterplot(x = y_test['mpg'], y = y_pred, ax=ax1)
  sns.regplot(x = y_test['mpg'], y=y_pred, ax=ax1)
  ax1.set_title("Log of Predictions vs. actuals")
  ax1.set_xlabel('Actual MPG')
  ax1.set_ylabel('predicted MPG')
  sns.scatterplot(x = np.exp(y_test['mpg']), y = np.exp(y_pred), ax=ax2,)
  sns.regplot(x = np.exp(y_test['mpg']), y=np.exp(y_pred), ax=ax2)
  ax2.set_title("Real values of Predictions vs. actuals")
  ax2.set_xlabel('Actual MPG')
  ax2.set_ylabel('predicted MPG')
